# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gta_code_converter_cpp <- function(codes_2012, codes_vintage, codes) {
    .Call(`_gtalibrary_gta_code_converter_cpp`, codes_2012, codes_vintage, codes)
}
