# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

datefunction <- function(start, end, current_date, current_year_todate = TRUE) {
    .Call(`_tet_datefunction`, start, end, current_date, current_year_todate)
}
